<?php
date_default_timezone_set('Asia/manila');

return [
		'dte_dateonly'			=> date('Y-m-d'),
		'dte_datetime'			=> date('Y-m-d H:i:s'),
		'asia_pacific'			=> [
			'AUS' => 'Australia',
			'BGD' => 'Bangladesh',
			'BTN' => 'Bhutan',
			'BRN' => 'Brunei',
			'KHM' => 'Cambodia',
			'CHN' => 'China',
			'COK' => 'Cook Islands',
			'FJI' => 'Fiji',
			'PYF' => 'French Polynesia',
			'HKG' => 'Hong Kong',
			'IND' => 'India',
			'IDN' => 'Indonesia',
			'JPN' => 'Japan',
			'KIR' => 'Kiribati',
			'LBN' => 'Lebanon',
			'MAC' => 'Macao',
			'MYS' => 'Malaysia',
			'MDV' => 'Maldives',
			'MHL' => 'Marshall Islands',
			'FSM' => 'Micronesia',
			'MNG' => 'Mongolia',
			'MMR' => 'Myanmar',
			'NRU' => 'Nauru',
			'NPL' => 'Nepal',
			'NZL' => 'New Zealand',
			'PLW' => 'Palau',
			'PNG' => 'Papua New Guinea',
			'PER' => 'Peru',
			'PHL' => 'Philippines',
			'RUS' => 'Russia',
			'WSM' => 'Samoa',
			'SGP' => 'Singapore',
			'SLB' => 'Solomon Islands',
			'KOR' => 'South Korea',
			'LKA' => 'Sri Lanka',
			'TWN' => 'Taiwan',
			'THA' => 'Thailand',
			'TLS' => 'Timor-Leste',
			'TON' => 'Tonga',
			'TUV' => 'Tuvalu',
			'VUT' => 'Vanuatu',
			'VNM' => 'Vietnam',
			'USA' => 'United States'
		]
	];